baseURL: "https://blog.nailak.com/"
title: "Nailak Blog"

description: "Beauty advice from the Nailak — learn how to create salon-quality results at home. Cuticle oil, strengthen nails, and cuticle oil"
theme: "PaperMod"
publishDir: "../docs"

# URL настройки
canonifyURLs: true
relativeURLs: true
uglyURLs: false
layoutDir: "layouts"

server:
  baseURLRedirects: false

pagination:
  pagerSize: 10

enableRobotsTXT: true
buildDrafts: false
buildFuture: true
buildExpired: false
enableGitInfo: true

frontmatter:
  date:
    - :filename
    - date
    - publishDate
    - :default
  lastmod:
    - lastmod
    - :default

permalinks:
  posts: "/posts/:year/:month/:day/:slug/"
slugify:
  mode: "ascii"
  lowercase: true

outputs:
  home:
    - HTML
    - RSS
    - JSON
    - Sitemap

taxonomies:
  category: categories
  tag: tags

params:
  disableAnchoredHeadings: true
  env: production
  title: "Nailak Blog"
  tagline: "Beauty and Wellness Tips"
  description: "Expert tips on nail and cuticle care, product insights, and self-care routines from Nailak — vegan, cruelty-free nail oil made in the USA."
  keywords: ["nail care", "cuticle oil", "nail oil", "vegan nail oil", "nail health", "Nailak", "hand care", "natural oils", "vitamin E", "squalane"]
  customFooterText: "© 2025 Nailak Blog. All rights reserved."
  defaultTheme: auto
  ShowReadingTime: true
  ShowWordCount: true
  centerTheme: true
  author: "Nailak Editorial"

  label:
    text: "Nailak"
    icon: "favicon.svg"
    iconHeight: 38

  assets:
    favicon: "favicon.svg"

  disableGA: true
  ShowRelatedPosts: true
  relatedPosts:
    count: 4
    threshold: 0
    includeNewer: true
    sortByDate: false

# Разрешаем вставку HTML в Markdown (нужно для <figure> и <img>)
markup:
  goldmark:
    renderer:
      unsafe: true

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1

    - identifier: shop
      name: Shop
      url: https://nailak.com/products
      weight: 2
