baseURL: "https://blog.nailak.com/"
title: "Nailak Blog"
theme: "PaperMod"
publishDir: "../docs"

# URL настройки
canonifyURLs: true
relativeURLs: true
uglyURLs: false
layoutDir: "layouts"

server:
  baseURLRedirects: false

pagination:
  pagerSize: 10

enableRobotsTXT: true
buildDrafts: false
buildFuture: true
buildExpired: false
enableGitInfo: true

frontmatter:
  date:
    - :filename
    - date
    - publishDate
    - :default
  lastmod:
    - lastmod
    - :default

permalinks:
  posts: "/posts/:year/:month/:day/:slug/"

outputs:
  home:
    - HTML
    - RSS
    - JSON
    - Sitemap

taxonomies:
  category: categories
  tag: tags

params:
  disableAnchoredHeadings: true
  env: production
  title: "Nailak Blog"
  description: "Expert tips on nail and cuticle care, product insights, and self-care routines from Nailak — vegan, cruelty-free nail oil made in the USA."
  keywords: ["nail care", "cuticle oil", "nail oil", "vegan nail oil", "nail health", "Nailak", "hand care", "natural oils", "vitamin E", "squalane"]
  customFooterText: "© 2025 Nailak Blog. All rights reserved."
  defaultTheme: auto
  ShowReadingTime: true
  ShowWordCount: true
  centerTheme: true

  params:
  author: "Nailak Editorial"

  label:
    text: "Nailak"
    icon: "favicon.svg"
    iconHeight: 64

  assets:
    favicon: "favicon.svg"

  disableGA: true
  ShowRelatedPosts: true
  relatedPosts:
    count: 4
    threshold: 0
    includeNewer: true
    sortByDate: false

privacy:
  googleAnalytics:
    anonymizeIP: true
  youtube:
    privacyEnhanced: true

related:
  threshold: 60
  includeNewer: true
  toLower: false
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 80

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 3

menu:
  main:
    - identifier: home
      name: Home
      url: "/"
      weight: 1
    - identifier: shop
      name: Shop
      url: "https://nailak.com/"
      weight: 2

  footer:
    - identifier: privacy
      name: Privacy Policy
      url: "/privacy-policy/"
      weight: 1
    - identifier: terms
      name: Terms of Service
      url: "/terms/"
      weight: 2
    - identifier: sitemap
      name: Sitemap
      url: "/sitemap.xml"
      weight: 3
