name: Blog Writer

on:
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * *'   # каждый день в 13:00 UTC

permissions:
  contents: write

jobs:
  writer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r blog_src/scripts/requirements.txt

      - name: Run generator (create Markdown posts)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python -m blog_src.scripts.writer.main

      - name: Commit & Push new posts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add blog_src/content/posts blog_src/data/state.json
          git commit -m "Add new blog post [skip ci]" || echo "No changes"
          git push
